spring:
  application:
    name: trabajo-aulas-is3
  datasource:
    url: jdbc:mysql://localhost:3306/trabajo-aulas-is3-grupo2
    username: root
    password: loquesea2008
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect