spring:
  application:
    name: is3_tp
  datasource:
    url: jdbc:mysql://localhost:3306/is3_tp
    username: root
    password: loquesea2008
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect